<?php
return [
    'app_env' => 'local',
    'app_url' => 'https://assessment.netcascade.in',
    'jwt_secret' => 'change-this-to-a-long-random-secret',
    'jwt_issuer' => 'assessment.netcascade.in',
    'jwt_ttl_seconds' => 7200,
    'cookie_secure' => true,
    'db_host' => 'localhost',
    'db_port' => null,
    'db_socket' => null,
    'db_name' => 'assessment',
    'db_user' => 'assessment_user',
    'db_pass' => 'change-me',
    'mail_driver' => 'mail',
    'app_error_log_path' => __DIR__ . '/../storage/logs/app-error.log',
    'mail_log_path' => __DIR__ . '/../storage/logs/mail.log',
    'mail_error_log_path' => __DIR__ . '/../storage/logs/mail-error.log',
    'mail_from' => 'no-reply@assessment.netcascade.in',
    'mail_from_name' => 'Assessment Platform',
    'smtp_host' => 'smtp.office365.com',
    'smtp_port' => 587,
    'smtp_secure' => 'tls',
    'smtp_username' => 'mailbox@example.com',
    'smtp_password' => 'change-me',
    'graph_tenant_id' => 'your-tenant-id-or-domain',
    'graph_client_id' => 'your-azure-app-client-id',
    'graph_client_secret' => 'your-azure-app-client-secret',
    'graph_sender' => 'mailbox@example.com',
    'graph_save_to_sent_items' => true,
];
